#!/usr/bin/env python3

import sys
import struct


def parse_message():
    length_bytes = sys.stdin.read(4)
    if not len(length_bytes):  # reached EOF
        sys.exit(0)

    length = struct.unpack("@i", length_bytes)[0]  # length : int32
    text = sys.stdin.read(length).decode("utf-8")  # text : UTF8String
    return text


def main(_):
    sys.stdin = sys.stdin.detach()

    while True:
        msg = parse_message()
        print(msg)


if __name__ == "__main__":
    main(sys.argv[1:])
