#!/usr/bin/env python3

import os
import sys

XDG_CACHE_HOME = os.environ.get("XDG_CACHE_HOME",
                                os.path.expanduser("~/.cache"))
CHEATPATH = os.path.join(XDG_CACHE_HOME, "font-awesome.txt")
CHEATURL = "http://fontawesome.io/cheatsheet"


def download_cheatsheet(fp):
    # Importing is slooow.  Doing it even when the cache exists is bad.
    import requests
    from bs4 import BeautifulSoup

    page = requests.get(CHEATURL)
    page.raise_for_status()

    bs = BeautifulSoup(page.text)
    icons = bs.select("div.container > div.row i.fa")
    cheatsheet = {i.next_sibling.strip()[3:]: i.string for i in icons}

    maxlen = max(len(k) for k in cheatsheet)
    cheatsheet = "\n".join("%*s  %s" % (maxlen, k, v)
                           for k, v in cheatsheet.items())
    fp.write(cheatsheet)


def find_codepoint(query, fp):
    for line in fp:
        name, code = line.split()
        if query == name:
            return code


def main(args):
    if not args:
        return 2

    try:
        cheatsheet = open(CHEATPATH)
    except FileNotFoundError:
        os.makedirs(os.path.dirname(CHEATPATH), exist_ok=True)
        with open(CHEATPATH, "w") as fp:
            download_cheatsheet(fp)
        cheatsheet = open(CHEATPATH)

    codepoint = find_codepoint(args[0], cheatsheet)
    if not codepoint:
        return 1

    print(codepoint)
    return 0

if __name__ == "__main__":
    # os._exit exits the interpreter *now*, bypassing any garbage collection
    # which the kernel will do anyway.
    os._exit(main(sys.argv[1:]))
