#!/bin/sh

for file; do
    mime=$(file -L -b --mime-type "$file")
    case "$mime" in
        image/svg+xml) inkscape -S "$file" ;;
        image/gif)     gifsicle -I "$file" ;;
        image/* )      mediainfo   "$file" ;;

        video/* | audio/* | application/vnd.rn-realmedia) mediainfo "$file" ;;

        application/pdf) pdfinfo "$file" ;;

        application/zip)   unzip -l "$file" ;;
        application/x-lha) lha -l   "$file" ;;
        application/x-rar) unrar lb "$file" ;;

        application/x-bittorrent) aria2c -S "$file" | grep '\./' ;;

        application/x-iso9660-image) isoinfo -J -l -i "$file" ;;

        *) case "$file" in
            *.torrent) aria2c -S "$file" | grep '\./' ;;

            *.mkv) mediainfo "$file" ;;

            *.ace) unace l "$file" ;;

            *.icns) icns2png -l "$file" ;;

            *) file -b "$file" ;;
        esac ;;
    esac
done
